<?php
/**
 * Test class for Enlight_Extensions_ErrorHandler_Bootstrap.
 * Generated by PHPUnit on 2012-01-20 at 15:48:07.
 */
class Enlight_Tests_Extensions_ErrorHandler_BootstrapTest extends Enlight_Components_Test_Plugin_TestCase
{
    /**
     * @var Enlight_Extensions_ErrorHandler_Bootstrap
     */
    protected $errorHandler;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->errorHandler = $this->getMock('Enlight_Extensions_ErrorHandler_Bootstrap', null, array(''));
        $namespace = new Enlight_Plugin_Namespace_Loader('Extensions');
        $namespace->registerPlugin($this->errorHandler);
        parent::setUp();
    }

    public function testInit()
    {
        $this->errorHandler->init();
        $this->assertArrayCount(16, $this->errorHandler->errorLevelList);

    }

    /**
     * @covers Enlight_Extensions_ErrorHandler_Bootstrap::install
     */
    public function testInstall()
    {
        $errorHandler = $this->getMock(
            'Enlight_Extensions_ErrorHandler_Bootstrap', array('subscribeEvent'),
            array(), '', false
        );

        $errorHandler->expects($this->once())
                     ->method('subscribeEvent')
                     ->with($this->isType('string'));

        $this->assertTrue($errorHandler->install());
    }

    /**
     * @covers Enlight_Extensions_ErrorHandler_Bootstrap::onStartDispatch
     */
    public function testStartDispatch()
    {
        $this->errorHandler->onStartDispatch();

        $this->assertTrue($this->errorHandler->registeredErrorHandler);

        $this->assertArrayCount(2, $this->errorHandler->origErrorHandler);
    }

    /**
     * @covers Enlight_Extensions_ErrorHandler_Bootstrap::registerErrorHandler
     */
    public function testRegisterErrorHandler()
    {
        $this->assertInstanceOf('Enlight_Extensions_ErrorHandler_Bootstrap', $this->errorHandler->registerErrorHandler());

        $this->assertTrue($this->errorHandler->registeredErrorHandler);

        $this->assertArrayCount(2, $this->errorHandler->origErrorHandler);
    }

    /**
     * @covers Enlight_Extensions_ErrorHandler_Bootstrap::setEnabledLog
     */
    public function testSetEnabledLog()
    {
        $this->errorHandler->setEnabledLog(true);
        $this->assertTrue($this->errorHandler->errorLog);
    }

}